=== lquenti/XMW/EXA/flush.dtd
<!ELEMENT root (Courses|Exams|Lecturers|Lectures|Semesters|Modules)*>
        <!ELEMENT Courses (Course)*>
        <!ELEMENT Course (name|faculty|max_students)*>
        <!ATTLIST Course
                id ID #REQUIRED
                lecturer IDREF #REQUIRED
                semester IDREF #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT faculty (#PCDATA)>
        <!ELEMENT max_students (#PCDATA)>
        <!ELEMENT Exams (Exam)*>
        <!ELEMENT Exam (date|is_online|is_written|room_or_link)*>
        <!ATTLIST Exam
                id ID #REQUIRED
                course IDREF #REQUIRED>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT is_online (#PCDATA)>
        <!ELEMENT is_written (#PCDATA)>
        <!ELEMENT room_or_link (#PCDATA)>
        <!ELEMENT Lecturers (Lecturer)*>
        <!ELEMENT Lecturer (firstname|name)*>
        <!ATTLIST Lecturer
                faculty CDATA #IMPLIED
                id ID #REQUIRED
                username CDATA #REQUIRED>
        <!ELEMENT firstname (#PCDATA)>
        <!ELEMENT Lectures (Lecture)*>
        <!ELEMENT Lecture (start|end|room_or_link)*>
        <!ATTLIST Lecture
                course IDREF #REQUIRED
                id ID #REQUIRED>
        <!ELEMENT start (#PCDATA)>
        <!ELEMENT end (#PCDATA)>
        <!ELEMENT Semesters (Semester)*>
        <!ELEMENT Semester (name|start|end)*>
        <!ATTLIST Semester
                id ID #REQUIRED>
        <!ELEMENT Modules (Module)*>
        <!ELEMENT Module (name|Studies|Description)*>
        <!ATTLIST Module
                id ID #REQUIRED
                credits CDATA #REQUIRED
                course IDREF #REQUIRED>
        <!ELEMENT Studies (Study)*>
        <!ELEMENT Study (#PCDATA)*>
        <!ELEMENT Description (#PCDATA)>

=== lquenti/XMW/EXA/flush.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root
        SYSTEM "flush.dtd" >
<root>
    <Courses>
        <Course id="16" lecturer="10" semester="3">
            <name>quia</name>
            <faculty>dolor</faculty>
            <max_students>123</max_students>
        </Course>
        <Course id="17" lecturer="9" semester="3">
            <name>voluptas</name>
            <faculty>officiis</faculty>
            <max_students>377</max_students>
        </Course>
        <Course id="18" lecturer="2" semester="3">
            <name>minus</name>
            <faculty>illum</faculty>
            <max_students>280</max_students>
        </Course>
        <Course id="19" lecturer="4" semester="3">
            <name>nobis</name>
            <faculty>est</faculty>
            <max_students>347</max_students>
        </Course>
        <Course id="20" lecturer="2" semester="3">
            <name>enim</name>
            <faculty>quo</faculty>
            <max_students>297</max_students>
        </Course>
        <Course id="21" lecturer="2" semester="3">
            <name>harum</name>
            <faculty>sed</faculty>
            <max_students>197</max_students>
        </Course>
        <Course id="22" lecturer="6" semester="3">
            <name>sunt</name>
            <faculty>delectus</faculty>
            <max_students>233</max_students>
        </Course>
        <Course id="23" lecturer="8" semester="4">
            <name>dicta</name>
            <faculty>optio</faculty>
            <max_students>161</max_students>
        </Course>
        <Course id="24" lecturer="9" semester="4">
            <name>sed</name>
            <faculty>dicta</faculty>
            <max_students>331</max_students>
        </Course>
        <Course id="25" lecturer="7" semester="4">
            <name>amet</name>
            <faculty>expedita</faculty>
            <max_students>28</max_students>
        </Course>
        <Course id="26" lecturer="6" semester="4">
            <name>velit</name>
            <faculty>et</faculty>
            <max_students>215</max_students>
        </Course>
        <Course id="27" lecturer="2" semester="4">
            <name>possimus</name>
            <faculty>voluptatem</faculty>
            <max_students>226</max_students>
        </Course>
        <Course id="34" lecturer="10" semester="1">
            <name>rerum</name>
            <faculty>omnis</faculty>
            <max_students>76</max_students>
        </Course>
    </Courses>
    <Exams>
        <Exam id="1" course="1">
            <date>2025-11-22T12:26:11</date>
            <is_online>1</is_online>
            <is_written>0</is_written>
            <room_or_link>http://robel.net/ipsa-enim-et-vel-ipsam-tempora-laborum.html</room_or_link>
        </Exam>
        <Exam id="2" course="2">
            <date>2025-11-17T12:21:22</date>
            <is_online>0</is_online>
            <is_written>1</is_written>
            <room_or_link>Room 82219</room_or_link>
        </Exam>
        <Exam id="3" course="3">
            <date>2026-01-06T12:55:07</date>
            <is_online>0</is_online>
            <is_written>0</is_written>
            <room_or_link>Room 2131</room_or_link>
        </Exam>
        <Exam id="4" course="4">
            <date>2026-01-22T12:44:18</date>
            <is_online>0</is_online>
            <is_written>1</is_written>
            <room_or_link>Room 3857</room_or_link>
        </Exam>
        <Exam id="5" course="4">
            <date>2026-02-19T14:34:02</date>
            <is_online>1</is_online>
            <is_written>1</is_written>
            <room_or_link>http://marks.com/</room_or_link>
        </Exam>
        <Exam id="6" course="5">
            <date>2025-12-10T08:59:09</date>
            <is_online>0</is_online>
            <is_written>0</is_written>
            <room_or_link>Room 61963</room_or_link>
        </Exam>
        <Exam id="7" course="5">
            <date>2026-01-17T19:37:33</date>
            <is_online>0</is_online>
            <is_written>0</is_written>
            <room_or_link>Room 972</room_or_link>
        </Exam>
        <Exam id="8" course="6">
            <date>2025-11-18T18:52:07</date>
            <is_online>1</is_online>
            <is_written>0</is_written>
            <room_or_link>http://gleason.com/</room_or_link>
        </Exam>
        <Exam id="9" course="7">
            <date>2025-08-28T07:41:13</date>
            <is_online>0</is_online>
            <is_written>1</is_written>
            <room_or_link>Room 1494</room_or_link>
        </Exam>
        <Exam id="10" course="7">
            <date>2025-06-20T03:34:36</date>
            <is_online>0</is_online>
            <is_written>1</is_written>
            <room_or_link>Room 4479</room_or_link>
        </Exam>
        <Exam id="11" course="8">
            <date>2025-09-12T12:06:47</date>
            <is_online>0</is_online>
            <is_written>0</is_written>
            <room_or_link>Room 3586</room_or_link>
        </Exam>
        <Exam id="12" course="8">
            <date>2025-06-08T04:50:38</date>
            <is_online>1</is_online>
            <is_written>1</is_written>
            <room_or_link>http://wyman.net/dicta-quibusdam-possimus-nihil</room_or_link>
        </Exam>
        <Exam id="13" course="9">
            <date>2025-09-01T05:03:13</date>
            <is_online>1</is_online>
            <is_written>1</is_written>
            <room_or_link>http://mohr.com/et-id-voluptas-explicabo-impedit-nulla.html</room_or_link>
        </Exam>
        <Exam id="14" course="10">
            <date>2025-05-02T00:23:24</date>
            <is_online>0</is_online>
            <is_written>0</is_written>
            <room_or_link>Room 527</room_or_link>
        </Exam>
        <Exam id="15" course="10">
            <date>2025-07-28T03:53:27</date>
            <is_online>0</is_online>
            <is_written>0</is_written>
            <room_or_link>Room 14981</room_or_link>
        </Exam>
        <Exam id="16" course="11">
            <date>2025-08-12T05:20:27</date>
            <is_online>0</is_online>
            <is_written>1</is_written>
            <room_or_link>Room 8604</room_or_link>
        </Exam>
        <Exam id="17" course="12">
            <date>2025-08-10T04:57:19</date>
            <is_online>0</is_online>
            <is_written>0</is_written>
            <room_or_link>Room 1169</room_or_link>
        </Exam>
        <Exam id="18" course="12">
            <date>2025-04-28T00:48:00</date>
            <is_online>1</is_online>
            <is_written>0</is_written>
            <room_or_link>http://www.klein.info/veniam-aperiam-fuga-voluptate-fuga-doloremque-error-qui-qui
            </room_or_link>
        </Exam>
        <Exam id="19" course="13">
            <date>2025-08-03T19:48:28</date>
            <is_online>0</is_online>
            <is_written>0</is_written>
            <room_or_link>Room 99326</room_or_link>
        </Exam>
        <Exam id="20" course="14">
            <date>2025-05-04T17:39:59</date>
            <is_online>1</is_online>
            <is_written>1</is_written>
            <room_or_link>http://harber.com/</room_or_link>
        </Exam>
        <Exam id="21" course="15">
            <date>2026-11-16T12:42:04</date>
            <is_online>0</is_online>
            <is_written>0</is_written>
            <room_or_link>Room 782</room_or_link>
        </Exam>
        <Exam id="22" course="16">
            <date>2027-01-25T12:35:21</date>
            <is_online>1</is_online>
            <is_written>0</is_written>
            <room_or_link>http://rosenbaum.org/beatae-explicabo-optio-illo-iusto-reprehenderit-earum.html</room_or_link>
        </Exam>
        <Exam id="23" course="16">
            <date>2027-01-31T06:21:10</date>
            <is_online>0</is_online>
            <is_written>0</is_written>
            <room_or_link>Room 20873</room_or_link>
        </Exam>
        <Exam id="24" course="17">
            <date>2027-01-05T19:42:24</date>
            <is_online>0</is_online>
            <is_written>1</is_written>
            <room_or_link>Room 5419</room_or_link>
        </Exam>
        <Exam id="25" course="18">
            <date>2026-11-11T00:02:36</date>
            <is_online>0</is_online>
            <is_written>0</is_written>
            <room_or_link>Room 563</room_or_link>
        </Exam>
        <Exam id="26" course="18">
            <date>2026-11-04T23:16:36</date>
            <is_online>0</is_online>
            <is_written>1</is_written>
            <room_or_link>Room 10655</room_or_link>
        </Exam>
        <Exam id="27" course="19">
            <date>2027-03-16T13:18:30</date>
            <is_online>0</is_online>
            <is_written>1</is_written>
            <room_or_link>Room 53194</room_or_link>
        </Exam>
        <Exam id="28" course="19">
            <date>2026-12-29T20:00:55</date>
            <is_online>0</is_online>
            <is_written>0</is_written>
            <room_or_link>Room 5508</room_or_link>
        </Exam>
        <Exam id="29" course="20">
            <date>2026-12-21T18:40:21</date>
            <is_online>0</is_online>
            <is_written>0</is_written>
            <room_or_link>Room 4069</room_or_link>
        </Exam>
        <Exam id="30" course="21">
            <date>2026-12-21T21:46:16</date>
            <is_online>1</is_online>
            <is_written>0</is_written>
            <room_or_link>http://www.krajcik.info/</room_or_link>
        </Exam>
        <Exam id="31" course="22">
            <date>2026-12-16T10:51:31</date>
            <is_online>0</is_online>
            <is_written>1</is_written>
            <room_or_link>Room 9393</room_or_link>
        </Exam>
        <Exam id="32" course="22">
            <date>2027-01-01T22:56:51</date>
            <is_online>0</is_online>
            <is_written>1</is_written>
            <room_or_link>Room 861</room_or_link>
        </Exam>
        <Exam id="33" course="23">
